CREATE VIEW `fcv_cobrancas` AS SELECT 
MD5(CONCAT(`id_faturafc`,`valor_faturafc`,`mes_faturafc`)) AS md5_cobrancasfc,
`id_faturafc` AS id_cobrancasfc,
`cliente_faturafc` AS nome_cliente_cobrancasfc,
`sit_cliente_faturafc` AS sit_cliente_cobrancasfc,
`email_faturafc` AS email_cobrancasfc,
`telefones_faturafc` AS telefones_cobrancasfc,
`mes_faturafc` AS mes_cobrancasfc,
`periodo_faturafc` AS periodo_cobrancasfc, 
`descricao_faturafc` AS descricao_cobrancasfc,
`vencimento_faturafc` AS vencimento_cobrancasfc,
IF(`vencimento_faturafc` < CURDATE(),'Vencida',IF(`vencimento_faturafc` = CURDATE(),'Vencendo hoje','A vencer')) AS text_sit_cobrancasfc,
`debitos_faturafc` AS debitos_cobrancasfc,
`descontos_faturafc` AS descontos_cobrancasfc,
`valor_faturafc` AS valor_cobrancasfc,
`pagamentos_creditos_faturafc` AS pagamentos_creditos_cobrancasfc,
`pago_faturafc` AS pago_cobrancasfc,
`ids_pg_faturafc` AS ids_pg_cobrancasfc,
`datas_pg_faturafc` AS datas_pg_cobrancasfc,
`tipo_pg_faturafc` AS tipo_pago_cobrancasfc,
`encargos_faturafc` AS encargos_cobrancasfc,
`valor_encargos_faturafc` AS valor_encargos_cobrancasfc,
IF((`valor_faturafc`+`valor_encargos_faturafc`-`pagamentos_creditos_faturafc`) < 0,0,ROUND(`valor_faturafc`+`valor_encargos_faturafc`-`pagamentos_creditos_faturafc`,2)) AS valor_atual_cobrancasfc,
ROUND(IF(`tipo_pg_faturafc`='MAIOR',`diferenca_faturafc`,0),2) AS creditos_cobrancasfc,
`sit_faturafc` AS sit_cobrancasfc,
`grupo_parceria` AS grupo_parceria,
`id_provedor` AS id_provedor
FROM `fcv_faturas`